---
- hosts: bastions
  become: yes
  become_method: sudo
  become_user: root
  ignore_errors: true

  tasks:
    - name: admin
      user: 
        name: "{{ item.name }}"
        groups: wheel
      with_items: "{{ users }}"
      when: ( "{{ item.grop }}" == 'admin' )
      loop: "{{ groups['adminnode'] }}"

    - name: webadmin
      user: 
        name: "{{ item.name }}"
        groups: apache
      with_items: "{{ users }}"
      when: ( "{{ item.grop }}" == 'webadmin' )
      loop: groups['webaserver']
# something that applies to all app servers.
