---
- hosts: localhost
  tasks:
    - name: admin
      debug: 
        msg: "User {{ item.key }} is {{ item.value.role }}" 
      loop: "{{ lookup('uss', uss) }}"


# something that applies to all app servers.
