---
- hosts: node1
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  
  tasks: 
    - name: installing nginx web server for testing purpose
      yum: 
        name: nginx
        state: installed
