---
- name: Adding users to groups
  user: 
    name: "{{ item[1].name }}"
    groups: "{{ item[0] }}" 
    append: yes
  with_nested: 
    - "{{ user_roles }}"
    - "{{ users }}"
  when: item[0] in item[1].group

  tags: 
    - add_user
#
