---
- name: Creating .ssh directory for the user
  file:
    path: /home/{{ item.name }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ users }}"

- name: Creating authorized_key file for user
  file:
    path: /home/{{ item.name }}/.ssh/authorized_keys
    state: touch
    mode: '0600'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ users }}"

- name: Placing public key in the authorized_keys file
  copy:
   content: "{{ item.pubkey }}"
   dest: /home/{{ item.name }}/.ssh/authorized_keys
  with_items: "{{ users }}"
